#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

LS_COLORS=$LS_COLORS:'di=0;35:' ; export LS_COLORS

# Aliases
alias poly='./.config/polybar/launch-polybar.sh > /dev/null 2>&1'
