#!/bin/bash
set -e 

IFACE="wlp3s0"
REQ_IP="192.168.1.44"
CONF="/etc/dhcp/dhclient-${IFACE}.conf"

# Ensure config file exists with requested address
sudo tee "$CONF" >/dev/null <<EOF
interface "$IFACE" {
    send dhcp-requested-address $REQ_IP;
}
EOF


sudo ip neigh flush dev $IFACE
sudo dhclient -r $IFACE
sudo dhclient $IFACE
